openapi: 3.0.0
info:
  title: NawthTech API
  version: 1.0.0
  description: API for NawthTech platform
  contact:
    name: NawthTech Team
    email: support@nawthtech.com

servers:
  - url: https://api.nawthtech.com/v1
    description: Production server
  - url: https://staging.api.nawthtech.com/v1
    description: Staging server

paths:
  # ================================
  # 👤 مصادقة المستخدمين (Authentication)
  # ================================
  /auth/register:
    post:
      summary: Register new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
                - phone
              properties:
                first_name:
                  type: string
                  minLength: 2
                  maxLength: 50
                last_name:
                  type: string
                  minLength: 2
                  maxLength: 50
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                phone:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Validation error
        '409':
          description: User already exists

  /auth/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '400':
          description: Validation error

  # ================================
  # 👤 ملف المستخدم (User Profile)
  # ================================
  /user/profile:
    get:
      summary: Get user profile
      tags:
        - Users
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
        '401':
          description: Unauthorized

    patch:
      summary: Update user profile
      tags:
        - Users
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                avatar_url:
                  type: string
                  format: uri
                bio:
                  type: string
                  maxLength: 500
                settings:
                  type: object
      responses:
        '200':
          description: Profile updated successfully
        '401':
          description: Unauthorized
        '400':
          description: Validation error

  # ================================
  # 👑 إدارة المستخدمين (Admin)
  # ================================
  /admin/users/{id}:
    patch:
      summary: Update user (Admin only)
      tags:
        - Admin
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                username:
                  type: string
                  minLength: 3
                  maxLength: 30
                  pattern: '^[a-zA-Z0-9_]+$'
                role:
                  type: string
                  enum: [user, admin, moderator]
                quota_text_tokens:
                  type: integer
                  minimum: 1
                quota_images:
                  type: integer
                  minimum: 1
                quota_videos:
                  type: integer
                  minimum: 1
                quota_audio_minutes:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: User updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not admin)
        '400':
          description: Validation error

  # ================================
  # 🛠️ الخدمات (Services)
  # ================================
  /services:
    post:
      summary: Create new service
      tags:
        - Services
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - price
                - category_id
              properties:
                title:
                  type: string
                  minLength: 5
                  maxLength: 100
                description:
                  type: string
                  minLength: 10
                  maxLength: 1000
                price:
                  type: number
                  minimum: 0
                category_id:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Service created successfully
        '401':
          description: Unauthorized
        '400':
          description: Validation error

  /services/{id}:
    patch:
      summary: Update service
      tags:
        - Services
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 100
                description:
                  type: string
                  maxLength: 500
                category:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                config:
                  type: object
                status:
                  type: string
                  enum: [pending, active, suspended, deleted]
      responses:
        '200':
          description: Service updated successfully
        '401':
          description: Unauthorized
        '400':
          description: Validation error

  # ================================
  # 🤖 الذكاء الاصطناعي (AI Generation)
  # ================================
  /ai/generate:
    post:
      summary: Generate AI content
      tags:
        - AI
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - prompt
              properties:
                prompt:
                  type: string
                  minLength: 1
                  maxLength: 5000
                provider:
                  type: string
                  enum: [gemini, openai, huggingface]
                  default: gemini
                model:
                  type: string
                type:
                  type: string
                  enum: [text, image]
                  default: text
                options:
                  type: object
      responses:
        '200':
          description: AI generation successful
        '401':
          description: Unauthorized
        '400':
          description: Validation error
        '429':
          description: Rate limit exceeded

  # ================================
  # 📁 الرفع (Uploads)
  # ================================
  /upload/image:
    post:
      summary: Upload image
      tags:
        - Uploads
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                public_id:
                  type: string
                folder:
                  type: string
                  default: nawthtech/uploads
                overwrite:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Image uploaded successfully
        '401':
          description: Unauthorized
        '400':
          description: Validation error
        '413':
          description: File too large

# ================================
# 🔐 الأمان (Security Schemes)
# ================================
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: string
        code:
          type: string

    ValidationError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string

    PaginatedResponse:
      type: object
      properties:
        data:
          type: array
          items: {}
        pagination:
          type: object
          properties:
            page:
              type: integer
            limit:
              type: integer
            total:
              type: integer
            total_pages:
              type: integer
            has_next:
              type: boolean
            has_prev:
              type: boolean

# ================================
# 🏷️ الوسوم (Tags)
# ================================
tags:
  - name: Authentication
    description: User authentication and registration
  - name: Users
    description: User profile management
  - name: Admin
    description: Administrative operations
  - name: Services
    description: Service management
  - name: AI
    description: AI generation services
  - name: Uploads
    description: File upload operations